const MASKS=[
 ["sunfang","Sunfang","EARLY","Lucha",1948,"Painted leather + cloth","Tall crown; narrow jaw taper","Silhouette first: the outline should read before decoration.","b94b3d"],
 ["kitsune-frame","Kitsune Frame","CLASSIC","Japan",1976,"Layered leather + fabric","Pointed fox-like side extensions","Implied shapes can be stronger than literal illustrations.","b86f35"],
 ["television-ghost","Television Ghost","HORROR","US",1983,"Soft latex + rigid brow","Human profile with elongated forehead","Small asymmetries can create unease without gore.","6f7274"],
 ["blue-comet","Blue Comet","CLASSIC","Mexico",1988,"Satin + leather","Compact aerodynamic profile","A limited palette can still be instantly memorable.","174ea6"],
 ["paper-moon","Paper Moon","EXPERIMENTAL","Global",1994,"Fabric + fiber texture","Round theatrical profile","A strange material choice can become the gimmick.","8b7760"],
 ["night-engine","Night Engine","MODERN","Japan",2007,"Synthetic leather + rubber","Low profile with rear fin","Modernity can come from construction, not neon.","a55d32"],
 ["carnival-saint","Carnival Saint","CLASSIC","Lucha",1965,"Embroidery + molded base","High crown and wide temple panels","Texture layering creates richness without clutter.","b13d35"],
 ["mirror-dog","Mirror Dog","MODERN","US",2012,"Suede + hard bridge","Human profile with strange forward plane","Comedy can come from commitment to a specific idea.","8b5e42"],
 ["red-room","Red Room","HORROR","Japan",2018,"Matte rubber shell","Compressed skull shape and heavy brow","Removing facial information can be more unsettling than adding it.","6f2422"],
 ["silver-static","Silver Static","EXPERIMENTAL","Global",2022,"Brushed fabric + metal trim","Almost featureless oval","A missing feature can become the focal point.","c58b3e"],
 ["jagged-sun","Jagged Sun","MODERN","Mexico",2015,"Satin + metallic embroidery","Radial silhouette built for movement","Directional shapes can make static gear look fast.","d7bd45"],
 ["last-clown","The Last Clown","HORROR","US",1991,"Latex + faded cotton","Broad cheeks and toy-like crown","Context can change how the same shape is perceived.","6d1f28"]
].map((x,i)=>({id:x[0],name:x[1],era:x[2],region:x[3],year:x[4],material:x[5],silhouette:x[6],lesson:x[7],accent:"#"+x[8],image:"assets/masks/"+x[0]+".svg",featured:i<3,underrated:i>7}));

const state={world:"HOME",mask:null,favorites:JSON.parse(localStorage.getItem("caw-helper-favorites")||"[]"),query:"",filter:"All",project:JSON.parse(localStorage.getItem("caw-helper-project")||"null")||{name:"NEW CAW",body:.55,shoulder:.55,waist:.45,skin:"#c99173",layers:["TRUNKS","BOOTS","KNEES","WRIST TAPE"]}};
const $=s=>document.querySelector(s);
const esc=s=>String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
function save(){localStorage.setItem("caw-helper-project",JSON.stringify(state.project));toast("PROJECT SAVED")}
function toast(t){const e=$("#toast");e.textContent=t;e.classList.add("show");clearTimeout(window.__toast);window.__toast=setTimeout(()=>e.classList.remove("show"),1500)}
function nav(world){state.world=world;render()}
function maskMatches(m){const q=state.query.toLowerCase();const text=(m.name+" "+m.era+" "+m.region+" "+m.material+" "+m.silhouette).toLowerCase();const cat=state.filter;return (!q||text.includes(q))&&(cat==="All"||m.era===cat||m.region===cat||(cat==="Under the Radar"&&m.underrated)||(cat==="Original"&&m.featured))}
function maskWall(){const visible=MASKS.filter(maskMatches);return `<section class="mask-world"><div class="archive-hero"><div><span class="eyebrow">THE ARCHIVE / MASK MAKER</span><h1>WALK THROUGH<br><em>WRESTLING HISTORY.</em></h1><p>A physical-feeling mask archive built for studying silhouette, material, construction and character identity. These are original study assets; verified historical references can be added as a future content layer.</p></div><div class="archive-stat"><b>${MASKS.length}</b><span>STUDY OBJECTS</span></div></div><div class="timeline"><span>1940</span><i></i><span>1960</span><i></i><span>1980</span><i></i><span>2000</span><i></i><span>2020</span></div><div class="mask-tools"><input id="mask-search" value="${esc(state.query)}" placeholder="SEARCH MASKS, MATERIALS, REGIONS..."><div class="chips">${["All","Lucha","Japan","Mexico","US","Classic","Modern","Horror","Experimental","Under the Radar"].map(c=>`<button class="${state.filter===c?"on":""}" data-filter="${c}">${c}</button>`).join("")}</div></div><div class="mask-wall">${visible.map((m,i)=>`<button class="mask-object ${state.favorites.includes(m.id)?"fav":""}" data-mask="${m.id}" style="--delay:${i*.04}s"><span class="pin"></span><img src="${m.image}" alt="${esc(m.name)}"><strong>${esc(m.name)}</strong><small>${m.year} / ${m.region}</small></button>`).join("")}</div></section>`}
function create(){return `<section class="page create"><div class="world-banner"><div><span class="eyebrow">CREATE-A-SUPERSTAR WORKSHOP</span><h1>BUILD THE<br><em>CHARACTER.</em></h1><p>A focused editor foundation with body proportions, skin, attire layers, palette, saving and export.</p></div><div class="figure"><div class="head"></div><div class="torso"></div><div class="legs"></div></div></div><div class="editor-grid"><aside><label>PROJECT NAME<input id="project-name" value="${esc(state.project.name)}"></label><h3>BODY</h3>${[["body","BUILD"],["shoulder","SHOULDER WIDTH"],["waist","WAIST"]].map(x=>`<label class="range">${x[1]}<output>${Math.round(state.project[x[0]]*100)}</output><input type="range" min="0" max="1" step=".01" value="${state.project[x[0]]}" data-body="${x[0]}"></label>`).join("")}<label>SKIN<input id="skin" type="color" value="${state.project.skin}"></label></aside><div class="editor-stage"><div class="gridlines"></div><div class="body-model" style="--build:${state.project.body};--shoulder:${state.project.shoulder};--waist:${state.project.waist};--skin:${state.project.skin}"><span class="body-head"></span><span class="body-chest"></span><span class="body-legs"></span></div><div class="stage-label">LIVE CHARACTER / LOCAL PREVIEW</div></div><aside><h3>ATTIRE LAYERS</h3>${["TRUNKS","BOOTS","KNEES","WRIST TAPE","ENTRANCE JACKET"].map(l=>`<button class="layer ${state.project.layers.includes(l)?"on":""}" data-layer="${l}"><span>${state.project.layers.includes(l)?"●":"○"}</span>${l}</button>`).join("")}<button class="wide" id="save">SAVE PROJECT</button><button class="wide ghost" id="export">EXPORT JSON</button></aside></div></section>`}
function explore(){return `<section class="page"><span class="eyebrow">EXPLORE / ORIGINAL STUDY COLLECTION</span><h1 class="big">THE DESIGN<br><em>LANGUAGE.</em></h1><div class="feature-grid">${MASKS.slice(0,6).map(m=>`<button class="feature" data-mask="${m.id}"><img src="${m.image}"><div><small>${m.era} / ${m.region}</small><h2>${m.name}</h2><p>${m.material}</p></div></button>`).join("")}</div></section>`}
function learn(){return `<section class="page learn"><span class="eyebrow">STUDY MODE / CAW DESIGN SCHOOL</span><h1 class="big">LEARN TO<br><em>SEE DESIGN.</em></h1><div class="lesson-grid"><article><b>01</b><h2>SILHOUETTE BEFORE DETAIL</h2><p>If the outline doesn't read from across the arena, adding graphics rarely fixes it. Study the outer shape first.</p></article><article><b>02</b><h2>MATERIAL IS CHARACTER</h2><p>Leather, satin, rubber, fabric and metal reflect light differently. Material choice can communicate era and personality.</p></article><article><b>03</b><h2>LIMIT THE PALETTE</h2><p>Two or three dominant colors often create a stronger identity than a crowded spectrum.</p></article></div></section>`}
function library(){return `<section class="page"><span class="eyebrow">LOCAL LIBRARY</span><h1 class="big">YOUR<br><em>WORK.</em></h1><div class="library-panel"><h2>${esc(state.project.name)}</h2><p>Saved locally in this browser. Export a JSON snapshot to move the project elsewhere.</p><button class="wide" id="save">SAVE CURRENT PROJECT</button><button class="wide ghost" id="export">EXPORT PROJECT JSON</button><hr><h3>FAVORITED MASK STUDIES</h3><div class="fav-list">${MASKS.filter(m=>state.favorites.includes(m.id)).map(m=>`<button data-mask="${m.id}">${m.name} — ${m.year}</button>`).join("")||"<p class='muted'>No favorites yet. Explore the Mask Maker.</p>"}</div></div></section>`}
function home(){return `<section class="home"><div class="home-image"></div><div class="home-copy"><span class="eyebrow">CAW CREATION / RESEARCH / DESIGN</span><h1>MAKE THE<br><em>CHARACTER.</em></h1><p>CAW Helper is a creation suite and wrestling design archive built around the feeling of entering a real game-world workshop.</p><div class="home-actions"><button class="hero-btn" data-go="CREATE">ENTER CREATION</button><button class="hero-btn outline" data-go="MASK MAKER">ENTER MASK MAKER</button></div></div><div class="home-strip"><span>01 / CREATE</span><span>02 / STUDY</span><span>03 / BUILD</span><span>04 / SAVE</span></div></section>`}
function modal(m){if(!m)return "";return `<div class="modal-backdrop" id="modal"><div class="modal"><button class="close" id="close">×</button><img src="${m.image}" alt=""><div><span class="eyebrow">${m.era} / ${m.region} / ${m.year}</span><h2>${m.name}</h2><p><b>SILHOUETTE</b><br>${m.silhouette}</p><p><b>MATERIAL</b><br>${m.material}</p><p><b>CREATOR LESSON</b><br>${m.lesson}</p><div class="modal-actions"><button class="wide" id="create-from">CREATE FROM THIS IDEA</button><button class="wide ghost" id="favorite">${state.favorites.includes(m.id)?"REMOVE FAVORITE":"ADD FAVORITE"}</button></div></div></div></div>`}
function render(){const root=$("#app");root.innerHTML=`<header><button class="logo" data-go="HOME"><span>✦</span> CAW <b>HELPER</b></button><nav>${["HOME","CREATE","MASK MAKER","EXPLORE","LEARN","LIBRARY"].map(x=>`<button class="${state.world===x?"active":""}" data-go="${x}">${x}</button>`).join("")}</nav><button class="save-top" id="save">SAVE</button></header><main>${state.world==="HOME"?home():state.world==="CREATE"?create():state.world==="MASK MAKER"?maskWall():state.world==="EXPLORE"?explore():state.world==="LEARN"?learn():library()}</main><div id="modal-root">${modal(state.mask)}</div><div id="toast"></div>`;bind()}
function bind(){document.querySelectorAll("[data-go]").forEach(b=>b.onclick=()=>nav(b.dataset.go));document.querySelectorAll("[data-mask]").forEach(b=>b.onclick=()=>{state.mask=MASKS.find(m=>m.id===b.dataset.mask);render()});$("#close")?.addEventListener("click",()=>{state.mask=null;render()});$("#modal")?.addEventListener("click",e=>{if(e.target.id==="modal"){state.mask=null;render()}});$("#favorite")?.addEventListener("click",()=>{const id=state.mask.id;state.favorites=state.favorites.includes(id)?state.favorites.filter(x=>x!==id):[...state.favorites,id];localStorage.setItem("caw-helper-favorites",JSON.stringify(state.favorites));toast(state.favorites.includes(id)?"ADDED TO FAVORITES":"REMOVED");render()});$("#create-from")?.addEventListener("click",()=>{state.project.name=state.mask.name+" — ORIGINAL";state.mask=null;nav("CREATE")});$("#mask-search")?.addEventListener("input",e=>{state.query=e.target.value;render();const q=$("#mask-search");q?.focus();q?.setSelectionRange(q.value.length,q.value.length)});document.querySelectorAll("[data-filter]").forEach(b=>b.onclick=()=>{state.filter=b.dataset.filter;render()});document.querySelectorAll("[data-body]").forEach(i=>i.oninput=()=>{state.project[i.dataset.body]=+i.value;render()});$("#project-name")?.addEventListener("change",e=>{state.project.name=e.target.value});$("#skin")?.addEventListener("input",e=>{state.project.skin=e.target.value;render()});document.querySelectorAll("[data-layer]").forEach(b=>b.onclick=()=>{const l=b.dataset.layer;state.project.layers=state.project.layers.includes(l)?state.project.layers.filter(x=>x!==l):[...state.project.layers,l];render()});document.querySelectorAll("#save").forEach(b=>b.onclick=save);document.querySelectorAll("#export").forEach(b=>b.onclick=()=>{const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(state.project,null,2)],{type:"application/json"}));a.download="caw-helper-project.json";a.click();toast("PROJECT EXPORTED")})}
render();