const MASKS = [
 ['ember-dragon','Ember Dragon','MODERN','Global','Dragon / Fire','Leather / Metallic','Angular','Sharp','Closed','Red / Gold / Black'],
 ['frost-phoenix','Frost Phoenix','MODERN','Japan','Phoenix / Ice','Leather / Satin','Tapered','Winged','Closed','White / Blue / Silver'],
 ['jungle-spirit','Jungle Spirit','EXPERIMENTAL','Mexico','Animal / Nature','Suede / Embossed','Organic','Wide','Open','Green / Black / Gold'],
 ['sol-invictus','Sol Invictus','CLASSIC','Mexico','Solar / Warrior','Leather / Metal','Radial','Almond','Closed','Gold / Ivory / Red'],
 ['void-walker','Void Walker','HORROR','Global','Unknown / Void','Rubber / Mesh','Compressed','Narrow','Closed','Violet / Black / Silver'],
 ['crimson-skull','Crimson Skull','HORROR','USA','Skull / Punk','Latex / Leather','Jagged','Deep','Open','Red / Black / Bone'],
 ['ocean-king','Ocean King','MODERN','Japan','Ocean / Hero','Satin / Leather','Flowing','Sharp','Closed','Blue / Gold / White'],
 ['shadow-fox','Shadow Fox','MODERN','Japan','Fox / Trickster','Leather / Suede','Pointed','Slit','Closed','White / Black / Red'],
 ['iron-serpent','Iron Serpent','EXPERIMENTAL','Global','Serpent / Armor','Brushed metal / Leather','Layered','Slanted','Closed','Gunmetal / Green'],
 ['celestial-guardian','Celestial Guardian','FANTASY','Global','Myth / Guardian','Metallic / Satin','Crowned','Round','Closed','Gold / White / Azure'],
 ['night-blossom','Night Blossom','MODERN','Japan','Flora / Night','Velvet / Leather','Petaled','Tapered','Closed','Magenta / Black / Violet'],
 ['blood-moon','Blood Moon','HORROR','Mexico','Moon / Ritual','Leather / Latex','Crescent','Deep','Open','Black / Red / Silver'],
 ['paper-tiger','Paper Tiger','EXPERIMENTAL','USA','Tiger / Graphic','Fabric / Fiber','Folded','Round','Open','Orange / Ivory / Ink'],
 ['glass-wraith','Glass Wraith','FUTURE','Global','Specter / Glass','Translucent polymer / mesh','Faceted','Long','Closed','Smoke / Cyan / Silver'],
 ['sun-eater','Sun Eater','FANTASY','Mexico','Solar / Predator','Leather / Brass','Fanged','Sharp','Covered','Amber / Black / Brass'],
 ['velvet-jester','Velvet Jester','COMEDY','USA','Theatre / Jester','Velvet / embroidery','Soft','Round','Grinning','Plum / Cream / Gold'],
 ['storm-ram','Storm Ram','MODERN','Japan','Ram / Storm','Rubber / metal','Horned','Heavy','Closed','Steel / Blue / White'],
 ['moon-viper','Moon Viper','HORROR','Global','Viper / Moon','Matte leather / satin','Serpentine','Slit','Closed','Silver / Violet / Black'],
 ['cinder-owl','Cinder Owl','ORIGINAL','Global','Owl / Ash','Suede / metal','Feathered','Large','Closed','Charcoal / Copper / Ivory'],
 ['white-noise','White Noise','ORIGINAL','USA','Signal / Abstract','Fabric / rubber','Asymmetric','Broken','Covered','White / Black / Grey']
].map((m,i)=>({id:m[0],name:m[1],era:m[2],region:m[3],style:m[4],material:m[5],silhouette:m[6],eyes:m[7],mouth:m[8],palette:m[9],image:`assets/generated/${m[0]}.jpg`,year:1950+i*4,featured:i<6}));

const DEFAULT_PROJECT={name:'UNTITLED CAW',base:'Full Face',eye:'Angular',mouth:'Covered',structure:'Layered',material:'Leather',primary:'#b51d26',secondary:'#d7b45a',detail:'#111111',pattern:'Directional',finish:'Satin',symmetry:62,scale:78,depth:72};
const state={world:'HOME',mask:null,query:'',filter:'ALL',favorites:JSON.parse(localStorage.getItem('caw-favs')||'[]'),projects:JSON.parse(localStorage.getItem('caw-projects')||'[]'),project:JSON.parse(localStorage.getItem('caw-current')||'null')||structuredClone(DEFAULT_PROJECT)};
const $=s=>document.querySelector(s);const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function persist(){localStorage.setItem('caw-favs',JSON.stringify(state.favorites));localStorage.setItem('caw-current',JSON.stringify(state.project));localStorage.setItem('caw-projects',JSON.stringify(state.projects))}
function toast(t){const e=$('#toast');if(!e)return;e.textContent=t;e.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>e.classList.remove('show'),1600)}
function nav(w){state.world=w;state.mask=null;render()}
function filtered(){const q=state.query.toLowerCase();return MASKS.filter(m=>(!q||(m.name+' '+m.era+' '+m.region+' '+m.style+' '+m.material).toLowerCase().includes(q))&&(state.filter==='ALL'||m.era===state.filter||m.region===state.filter||m.style.split(' / ')[0]===state.filter))}
function navBar(){return `<header class="top"><button class="brand" data-go="HOME"><span>CAW</span><b>HELPER</b></button><nav>${['HOME','CREATE','MASK MAKER','BODY','ATTIRE','ACCESSORIES','EXPLORE','LEARN','LIBRARY'].map(x=>`<button data-go="${x}" class="${state.world===x?'active':''}">${x}</button>`).join('')}</nav><div class="top-actions"><button id="saveTop">SAVE</button><button data-go="LIBRARY">◉</button></div></header>`}
function home(){return `<section class="home-world"><div class="home-art"></div><div class="home-overlay"></div><div class="home-copy"><span class="kicker">CREATE • DESIGN • EXPLORE • LEARN • BUILD</span><h1>CAW<br><em>HELPER</em></h1><p>A creator's world for building original wrestling characters, studying design language, and turning inspiration into a playable CAW workflow.</p><div class="home-actions"><button class="gold" data-go="MASK MAKER">ENTER THE MASK WORLD</button><button class="outline" data-go="CREATE">START A CAW</button></div></div><div class="home-corners"><span>01 / CREATE</span><span>02 / STUDY</span><span>03 / BUILD</span><span>04 / SAVE</span></div></section>`}
function categoryRail(){return `<div class="world-rail"><div class="rail-title">MASK MAKER</div>${[['MASK MAKER','MASK WALL'],['TIMELINE','TIMELINE'],['BUILDER','MASK BUILDER'],['STUDY','STUDY MODE'],['LIBRARY','MY DESIGNS']].map(([a,b])=>`<button class="rail-item ${a==='MASK MAKER'?'active':''}" data-mode="${a}"><span>${b}</span><i></i></button>`).join('')}<div class="rail-sep"></div><small>QUICK FILTERS</small>${['ALL','CLASSIC','MODERN','HORROR','FANTASY','COMEDY','ORIGINAL'].map(x=>`<button class="rail-filter ${state.filter===x?'on':''}" data-filter="${x}">${x}</button>`).join('')}</div>`}
function maskWorld(){const list=filtered();const sel=state.mask||list[0]||MASKS[0];return `<section class="mask-world"><div class="mask-bg"></div><div class="mask-shade"></div>${categoryRail()}<div class="mask-content"><div class="mask-heading"><div><span class="kicker">THE MASK WALL</span><h1>EXPLORE. <em>STUDY.</em> CREATE.</h1><p>Every object in this archive is an original CAW Helper study asset. Nothing here is a traced or copied historical mask.</p></div><div class="searchbox"><input id="search" value="${esc(state.query)}" placeholder="Search masks, styles, eras..."><span>${list.length} OBJECTS</span></div></div><div class="era-track"><span>ANCIENT ROOTS</span><i></i><span>GOLDEN ERA</span><i></i><span>MODERN LUCHA</span><i></i><span>GLOBAL EVOLUTION</span><i></i><span>FUTURE</span></div><div class="mask-stage-grid"><div class="wall">${list.map((m,i)=>`<button class="mask-card ${sel.id===m.id?'selected':''}" data-mask="${m.id}" style="--i:${i}"><div class="pin"></div><div class="mask-card-img"><img src="${m.image}" alt="${esc(m.name)}"></div><strong>${esc(m.name)}</strong><small>${m.era} / ${m.region}</small></button>`).join('')}</div><aside class="inspector"><div class="inspector-preview"><div class="turntable" id="turntable"><img src="${sel.image}" alt=""><div class="ring"></div></div><span class="view-badge">360° VIEW</span></div><div class="inspector-body"><div class="kicker">${sel.era} • ${sel.region}</div><h2>${esc(sel.name)}</h2><p>Original study object built around <b>${esc(sel.style)}</b>, with ${esc(sel.material.toLowerCase())} and a ${esc(sel.silhouette.toLowerCase())} silhouette.</p><div class="specs">${[['ERA',sel.era],['REGION',sel.region],['STYLE',sel.style],['MATERIAL',sel.material],['SILHOUETTE',sel.silhouette],['EYES',sel.eyes],['MOUTH',sel.mouth],['PALETTE',sel.palette]].map(x=>`<div><small>${x[0]}</small><b>${esc(x[1])}</b></div>`).join('')}</div><div class="inspector-actions"><button class="gold" id="createIdea">CREATE FROM THIS IDEA</button><button class="ghost" id="fav">${state.favorites.includes(sel.id)?'♥ SAVED':'♡ ADD TO FAVORITES'}</button><button class="ghost" id="study">STUDY THIS MASK</button></div></div></aside></div><div class="world-footer"><div><b>HISTORICAL TIMELINE</b><small>Travel through design eras without pretending original concepts are historical artifacts.</small></div><div class="timeline-dots">${[1940,1960,1980,2000,2020].map(y=>`<button data-year="${y}">${y}</button>`).join('')}</div></div></div></section>`}
function builder(){const p=state.project;const options={base:['Full Face','Half Mask','Open Face','Helmet'],eye:['Angular','Round','Slit','Winged'],mouth:['Covered','Closed','Open','Grinning'],structure:['Layered','Smooth','Horned','Faceted'],material:['Leather','Satin','Rubber','Metallic'],pattern:['Directional','Radial','Broken','Organic'],finish:['Matte','Satin','Gloss']};return `<section class="builder-world"><div class="builder-backdrop"></div><div class="builder-header"><span class="kicker">MASK BUILDER / ORIGINALS ONLY</span><h1>SHAPE THE <em>OBJECT.</em></h1><p>Choose construction language, not somebody else's design. The preview responds instantly.</p></div><div class="builder-layout"><aside class="builder-controls"><label>PROJECT NAME<input id="pname" value="${esc(p.name)}"></label>${Object.entries(options).map(([key,vals])=>`<div class="control-group"><span>${key.toUpperCase()}</span><div class="option-row">${vals.map(v=>`<button class="opt ${p[key]===v?'on':''}" data-opt="${key}" data-value="${v}">${v}</button>`).join('')}</div></div>`).join('')}<div class="color-row">${[['primary','PRIMARY'],['secondary','SECONDARY'],['detail','DETAIL']].map(x=>`<label>${x[1]}<input type="color" data-color="${x[0]}" value="${p[x[0]]}"></label>`).join('')}</div><div class="range-row"><label>DEPTH <input type="range" data-range="depth" min="20" max="100" value="${p.depth}"></label><label>SCALE <input type="range" data-range="scale" min="50" max="100" value="${p.scale}"></label></div><div class="builder-actions"><button class="gold" id="saveProject">SAVE VERSION</button><button class="ghost" id="newProject">NEW VERSION</button><button class="ghost" id="exportProject">EXPORT JSON</button></div></aside><main class="builder-stage"><div class="stage-grid"></div><div class="mask-model-wrap" id="builderModel"><div class="mask-model" style="--primary:${p.primary};--secondary:${p.secondary};--detail:${p.detail};--depth:${p.depth}px;--scale:${p.scale/100}"><div class="model-glow"></div><img src="${state.mask?.image||MASKS[0].image}" alt="custom mask preview"></div></div><div class="stage-readout"><b>${esc(p.name)}</b><span>LIVE ORIGINAL / ${p.material.toUpperCase()} / ${p.structure.toUpperCase()}</span></div></main></div></section>`}
function createWorld(){return `<section class="create-world"><div class="create-hero"><span class="kicker">CREATE-A-SUPERSTAR WORKSHOP</span><h1>BUILD THE<br><em>WHOLE THING.</em></h1><p>Character identity, body, attire, moveset, entrance and victory are one connected project.</p></div><div class="system-grid">${[['BODY','Shape, proportions, face, skin and presence.','BODY'],['ATTIRE','Layers, materials, colors, logos and masks.','ATTIRE'],['MOVES','Moveset, signatures, finishers and taunts.','MOVES'],['ENTRANCE','Music, motion, lighting and presentation.','ENTRANCE'],['VICTORY','Victory motion, pose and camera language.','VICTORY'],['SHEET','Name, stats, alignment, bio and export.','LIBRARY']].map(x=>`<button class="system-card" data-go="${x[2]==='BODY'?'BODY':x[2]==='ATTIRE'?'ATTIRE':'LIBRARY'}"><span>${x[0]}</span><h2>${x[1]}</h2><b>OPEN →</b></button>`).join('')}</div></section>`}
function genericWorld(title,sub,items){return `<section class="generic-world"><div class="generic-art"></div><div class="generic-inner"><span class="kicker">CAW HELPER / ${title}</span><h1>${title}<br><em>WORKSHOP.</em></h1><p>${sub}</p><div class="generic-grid">${items.map((x,i)=>`<article style="--n:${i}"><b>0${i+1}</b><h2>${x[0]}</h2><p>${x[1]}</p><button class="ghost">OPEN WORKSPACE</button></article>`).join('')}</div></div></section>`}
function explore(){return genericWorld('EXPLORE','A living index of original studies, creator techniques and collections built for discovery rather than imitation.',[['ORIGINALS','Browse the newest CAW Helper study objects.'],['COLLECTIONS','Group masks, body ideas, attire systems and references.'],['CREATOR NOTES','See why a design works: silhouette, material, rhythm and contrast.']])}
function learn(){return genericWorld('LEARN','Study silhouette, material, color, proportion, construction and character identity through repeatable exercises.',[['SILHOUETTE','Reduce a design until its outline carries the identity.'],['MATERIAL','Learn how leather, satin, rubber, metal and fabric change light.'],['COMPOSITION','Build a palette and hierarchy that survives the arena.']])}
function library(){return `<section class="library-world"><div class="library-inner"><span class="kicker">LOCAL LIBRARY / VERSIONED WORK</span><h1>YOUR <em>WORLD.</em></h1><div class="saved-projects">${state.projects.map((p,i)=>`<button class="saved" data-load="${i}"><b>${esc(p.name)}</b><small>VERSION ${i+1} • ${p.material} • ${p.structure}</small></button>`).join('')||'<div class="empty">No saved versions yet. Build something and save a version.</div>'}</div><button class="gold" data-go="BUILDER">OPEN MASK BUILDER</button></div></section>`}
function modal(){if(!state.mask)return '';const m=state.mask;return `<div class="modal" id="modal"><div class="modal-card"><button class="close" id="close">×</button><div class="modal-visual"><div class="modal-turn" id="modalTurn"><img src="${m.image}" alt=""></div><span>DRAG TO ROTATE • SCROLL TO ZOOM</span></div><div class="modal-info"><span class="kicker">ORIGINAL STUDY OBJECT</span><h2>${esc(m.name)}</h2><p>This object is a generated original for CAW Helper. Use it to study decisions, then create a new design rather than reproducing it.</p><div class="specs">${[['STYLE',m.style],['REGION',m.region],['MATERIAL',m.material],['SILHOUETTE',m.silhouette],['EYES',m.eyes],['MOUTH',m.mouth],['PALETTE',m.palette]].map(x=>`<div><small>${x[0]}</small><b>${esc(x[1])}</b></div>`).join('')}</div><button class="gold" id="modalBuild">CREATE FROM THIS IDEA</button></div></div></div>`}
function render(){let body=state.world==='HOME'?home():state.world==='CREATE'?createWorld():state.world==='MASK MAKER'?maskWorld():state.world==='BODY'?genericWorld('BODY','An anatomy-first workshop for proportion, silhouette, presence and physical character language.',[['PROPORTION','Height, shoulder, waist and stance studies.'],['FACE','Likeness, asymmetry and readable expressions.'],['PRESENCE','How scale and posture change a character before attire.']]):state.world==='ATTIRE'?genericWorld('ATTIRE','Build a coherent wardrobe around the character instead of stacking random pieces.',[['BASE LAYER','Tights, trunks, pads and foundational shapes.'],['MATERIALS','Leather, fabric, satin, rubber, metal and finish.'],['IDENTITY','Color blocking, motifs, symbols and signature pieces.']]):state.world==='ACCESSORIES'?genericWorld('ACCESSORIES','Finish the silhouette with deliberate objects: gloves, chains, glasses, belts and props.',[['HAND','Gloves, wraps and wrist language.'],['HEAD','Masks, glasses, hair and head pieces.'],['SIGNATURE','One object that makes the character instantly readable.']]):state.world==='EXPLORE'?explore():state.world==='LEARN'?learn():state.world==='LIBRARY'?library():state.world==='BUILDER'?builder():home();$('#app').innerHTML=navBar()+`<main>${body}</main>${modal()}<div id="toast"></div>`;bind()}
function bind(){document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>nav(b.dataset.go));document.querySelectorAll('[data-mask]').forEach(b=>b.onclick=()=>{state.mask=MASKS.find(m=>m.id===b.dataset.mask);render()});document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{state.filter=b.dataset.filter;render()});$('#search')?.addEventListener('input',e=>{state.query=e.target.value;render();$('#search')?.focus()});$('#close')?.addEventListener('click',()=>{state.mask=null;render()});$('#modal')?.addEventListener('click',e=>{if(e.target.id==='modal'){state.mask=null;render()}});$('#createIdea')?.addEventListener('click',()=>{state.world='BUILDER';state.project.name=state.mask.name+' / ORIGINAL';persist();render()});$('#modalBuild')?.addEventListener('click',()=>{state.world='BUILDER';state.project.name=state.mask.name+' / ORIGINAL';persist();render()});$('#fav')?.addEventListener('click',()=>{const id=(state.mask||filtered()[0]).id;state.favorites=state.favorites.includes(id)?state.favorites.filter(x=>x!==id):[...state.favorites,id];persist();render()});$('#study')?.addEventListener('click',()=>toast('STUDY MODE ARMED — BREAK DOWN THE SILHOUETTE FIRST'));$('#saveTop')?.addEventListener('click',saveCurrent);document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>nav(b.dataset.mode==='BUILDER'?'BUILDER':'MASK MAKER'));document.querySelectorAll('[data-opt]').forEach(b=>b.onclick=()=>{state.project[b.dataset.opt]=b.dataset.value;persist();render()});document.querySelectorAll('[data-color]').forEach(b=>b.oninput=()=>{state.project[b.dataset.color]=b.value;persist();render()});document.querySelectorAll('[data-range]').forEach(b=>b.oninput=()=>{state.project[b.dataset.range]=+b.value;persist();render()});$('#pname')?.addEventListener('input',e=>{state.project.name=e.target.value;persist()});$('#saveProject')?.addEventListener('click',saveCurrent);$('#newProject')?.addEventListener('click',()=>{state.project=structuredClone(DEFAULT_PROJECT);state.project.name='NEW ORIGINAL '+(state.projects.length+1);persist();render()});$('#exportProject')?.addEventListener('click',exportProject);document.querySelectorAll('[data-load]').forEach(b=>b.onclick=()=>{state.project=structuredClone(state.projects[+b.dataset.load]);persist();nav('BUILDER')});enableTurntables()}
function saveCurrent(){state.projects=[...state.projects.filter(p=>p.name!==state.project.name),structuredClone(state.project)].slice(-30);persist();toast('VERSION SAVED');render()}
function exportProject(){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify({version:1,project:state.project},null,2)],{type:'application/json'}));a.download=(state.project.name||'caw-helper').replace(/[^a-z0-9]+/gi,'-').toLowerCase()+'.json';a.click();toast('PROJECT EXPORTED')}
function enableTurntables(){document.querySelectorAll('#turntable,#modalTurn,#builderModel').forEach(el=>{let down=false,last=0,ry=0;el.addEventListener('pointerdown',e=>{down=true;last=e.clientX;el.setPointerCapture(e.pointerId)});el.addEventListener('pointerup',()=>down=false);el.addEventListener('pointermove',e=>{if(!down)return;ry+=(e.clientX-last)*.45;last=e.clientX;el.style.setProperty('--rot',ry+'deg')});el.addEventListener('wheel',e=>{e.preventDefault();const z=Math.max(.72,Math.min(1.45,(parseFloat(getComputedStyle(el).getPropertyValue('--zoom'))||1)-e.deltaY*.0008));el.style.setProperty('--zoom',z)},{passive:false})})}
render();